"use client";
import { useEffect, useRef, useState } from "react";
import { useSimulation } from "../src/store";
import type { Action, Location } from "../lib/runtime/types";

const positions:Record<Location,{left:string;top:string;label:string}>={reactor_room:{left:"25%",top:"25%",label:"Reactor Room"},storage_room:{left:"75%",top:"25%",label:"Storage"},corridor:{left:"25%",top:"75%",label:"Corridor"},security:{left:"75%",top:"75%",label:"Security"}};
const human:Record<Action,(target:string)=>string>={move:t=>`Maya walked to ${positions[t as Location]?.label??t}.`,pickup:()=>"Maya picked up the fuse.",talk:t=>`Maya spoke to the ${t}.`,inspect:t=>`Maya inspected the ${t}.`,repair:()=>"Maya repaired the reactor."};
const nextAction:Record<Action,{icon:string;label:string}>={move:{icon:"→",label:"WALK TO"},pickup:{icon:"+",label:"PICK UP FUSE"},talk:{icon:"◦",label:"SPEAK TO PLAYER"},inspect:{icon:"⌕",label:"INSPECT"},repair:{icon:"×",label:"REPAIR REACTOR"}};
const roomName=(target:string)=>positions[target as Location]?.label??target.replace(/_/g," ");

export default function Home(){
 const s=useSimulation();const [walking,setWalking]=useState(false);const [acting,setActing]=useState(false);const previousRoom=useRef(s.world.maya);const previousCall=useRef<string|undefined>();
 useEffect(()=>{if(previousRoom.current!==s.world.maya){previousRoom.current=s.world.maya;setWalking(true);const timer=setTimeout(()=>setWalking(false),900);return()=>clearTimeout(timer)}},[s.world.maya]);
 useEffect(()=>{const call=s.toolCalls[0];if(call&&call.timestamp!==previousCall.current){previousCall.current=call.timestamp;setActing(true);const timer=setTimeout(()=>setActing(false),1100);return()=>clearTimeout(timer)}},[s.toolCalls]);
 useEffect(()=>{if(!s.autoRun||s.loading)return;const timer=setTimeout(()=>s.stepAI(),1700);return()=>clearTimeout(timer)},[s.autoRun,s.loading,s.world,s.stepAI]);
 const call=s.toolCalls[0]; const action=s.decision?nextAction[s.decision.action]:{icon:"✨",label:"OBSERVE THE STATION"}; const visualState=s.loading?"thinking":walking?"walking":acting?"acting":"idle";
 const status=s.loading?"Maya is thinking about the station…":walking?`🚶 Maya is walking to ${roomName(s.world.maya)}…`:acting&&call?human[call.name](call.target):call?`✅ ${human[call.name](call.target)}`:"Maya is ready to help.";
 return <main className="sim"><header><div><div className="brand">OPEN<span>FORGE</span></div><div className="product">NPC SIMULATION <i>●</i> LIVE</div></div><p>A small station, a real decision-maker, and rules that hold.</p><div className={`source ${s.mode}`}><small>{s.mode==="local"?"LOCAL MODEL":"MOCK MODE"}</small><b>{s.mode==="local"?s.model:"Deterministic demo"}</b></div></header>
 <section className="world"><div className="section-label">STATION MAP <span>LIVE STATE</span></div><div className="station"><div className="room reactor-room"><RoomTitle icon="⚡" title="REACTOR ROOM"/><div className={`reactor ${s.world.reactor}`}><span>{s.world.reactor==="unstable"?"⚡":"✓"}</span><b>{s.world.reactor==="unstable"?"UNSTABLE":"STABLE"}</b><small>{s.world.reactor==="unstable"?"Needs a replacement fuse":"Power restored"}</small></div></div><div className="room storage"><RoomTitle icon="▣" title="STORAGE"/><div className="shelf">PARTS &amp; SUPPLIES</div></div><div className="room corridor"><RoomTitle icon="↔" title="CORRIDOR"/><div className="hall">STATION ACCESS</div></div><div className="room security"><RoomTitle icon="◈" title="SECURITY"/><div className="security-panel">SYSTEMS<br/>ONLINE</div></div>
   <Actor className={`maya ${visualState}`} pos={positions[s.world.maya]}><Marker type="maya"/><b>MAYA</b>{visualState==="thinking"&&<i className="dots"><u/> <u/> <u/></i>}{visualState==="acting"&&<i className="tool">{call?.name==="repair"?"×":"·"}</i>}</Actor>
   <Actor className="player" pos={positions[s.world.player]}><Marker type="player"/><b>PLAYER</b>{s.world.fuse==="player"&&<i className="carried">▰</i>}</Actor>
   <Actor className="alex" pos={positions[s.world.alex]}><Marker type="alex"/><b>ALEX</b></Actor>
   {s.world.fuse!=="player"&&s.world.fuse!=="maya"&&<div className="fuse" style={{left:positions[s.world.fuse as Location].left,top:positions[s.world.fuse as Location].top}}><span/> <b>FUSE</b></div>}{s.world.fuse==="maya"&&<div className="fuse carried-maya" style={{left:positions[s.world.maya].left,top:positions[s.world.maya].top}}><span/></div>}
  </div></section>
 <section className="maya-panel"><div className="maya-head"><Marker type="maya"/><div><small>MAYA · STATION ENGINEER</small><b>{visualState.toUpperCase()}</b></div></div><div className="thought"><small>MAYA'S ASSESSMENT</small><p>{s.decision?.thought??"Maya is watching the station and deciding what to do."}</p></div><div className="next"><small>NEXT MOVE</small><strong>{action.icon} {action.label}{s.decision?.action==="move"&&<em> {roomName(s.decision.target).toUpperCase()}</em>}</strong><p>{status}</p></div><button className="let-act" onClick={s.stepAI} disabled={s.loading}>{s.loading?"MAYA IS THINKING…":"▶ LET MAYA ACT"}</button></section>
 <section className="controls"><span>CHANGE THE WORLD</span><button onClick={s.takeFuse} disabled={s.world.fuse!=="storage_room"}>TAKE FUSE</button><button onClick={s.returnFuse} disabled={s.world.fuse!=="player"}>RETURN FUSE</button><button onClick={s.damageReactor}>DAMAGE REACTOR</button><button onClick={s.reset}>RESET</button><label>AI MODE <select value={s.mode} onChange={e=>s.setMode(e.target.value as "local"|"mock")}><option value="local">LOCAL AI</option><option value="mock">MOCK</option></select></label></section>{s.error&&<div className="offline"><b>OLLAMA OFFLINE</b> {s.error}<code>ollama serve && ollama pull qwen3:4b</code></div>}
 <details className="developer"><summary>⌄ &nbsp; Developer Details <small>MODEL, JSON, MEMORY &amp; EVENTS</small></summary><div className="dev-grid"><Dev title="MODEL"><p>{s.mode==="local"?`Local open-weight · ${s.model}`:"Mock / deterministic mode"}</p></Dev><Dev title="CURRENT JSON DECISION"><pre>{JSON.stringify(s.decision,null,2)}</pre></Dev><Dev title="LAST TOOL CALL"><pre>{call?`${call.name}("${call.target}")\n${call.result}`:"No tool call yet."}</pre></Dev><Dev title="MEMORY"><ul>{s.memories.slice(0,5).map(m=><li key={m.id}>{m.text}</li>)}</ul></Dev><Dev title="EVENT STREAM"><ul>{s.events.slice(0,7).map(e=><li key={e.id}><time>{e.timestamp}</time>{e.text}</li>)}</ul></Dev><Dev title="MODEL CONTEXT"><pre>{JSON.stringify(s.context??{agent:"Maya",world:s.world,memories:s.memories.slice(0,5),recent_events:s.events.slice(0,5)},null,2)}</pre></Dev></div></details></main>;
}
function RoomTitle({icon,title}:{icon:string;title:string}){return <div className="room-title"><span>{icon}</span>{title}</div>}
function Actor({className,pos,children}:{className:string;pos:{left:string;top:string};children:React.ReactNode}){return <div className={`actor ${className}`} style={{left:pos.left,top:pos.top}}>{children}</div>}
function Marker({type}:{type:"maya"|"player"|"alex"}){return <span className={`marker ${type}`}><i/></span>}
function Dev({title,children}:{title:string;children:React.ReactNode}){return <div className="dev"><h3>{title}</h3>{children}</div>}
